name: Zain
favicon: null
layout_spectrum: 0.1935484
typography_spectrum: 0.5035842
title: 'ZC Talent8 - Specialist Engineering, Rail, Property & Construction Talent Acquisition. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#177EED'
    - '#09325D'
    - '#1265BD'
  brandStrength: 1
  lightness: 0.6433692
  saturation: 1
  rhythmicContrast: 0.9909469
purpose: []
