name: Zain
favicon: null
layout_spectrum: 0.25145
typography_spectrum: 0.50578
title: 'ZC Talent8 - Specialist Engineering, Rail, Property & Construction Talent Acquisition. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#177EED'
    - '#09325D'
    - '#1265BD'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
