title: 'ZC Talent8 - Specialist Engineering, Rail, Property & Construction Talent Acquisition. '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7473118
  brandStrength: 1
  lightness: 0.5734767
  brandColors:
    - '#040504'
    - '#FCFCF3'
    - '#878965'
    - '#434DEA'
    - '#65F1BF'
  rhythmicContrast: 0.8387097
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Zain
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.50578
layout_spectrum: 0.3261649
